"""
evaluate.py — Metrics, plots and model selection report.

Run standalone after train.py has produced cv_results.csv:
    python -m spam_detector.evaluate
"""

from __future__ import annotations

import logging
import sys
from pathlib import Path

import pandas as pd

if __name__ == "__main__":
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from spam_detector.config import MODELS_DIR, REPORTS_DIR

logger = logging.getLogger(__name__)


def load_cv_results() -> pd.DataFrame:
    """Load cross-validation results from train.py output."""
    path = MODELS_DIR / "cv_results.csv"
    if not path.exists():
        raise FileNotFoundError(
            f"CV results not found at {path}.\n"
            "Run: python -m spam_detector.train"
        )
    return pd.read_csv(path)


def format_results_table(df: pd.DataFrame) -> str:
    """Format CV results as a Markdown table for README / reports."""
    display = df[[
        "normalisation", "classifier",
        "cv_f1_spam_mean", "cv_f1_spam_std",
        "cv_recall_spam_mean", "cv_precision_spam_mean",
        "cv_roc_auc_mean", "cv_accuracy_mean",
    ]].copy()

    display.columns = [
        "Normalisation", "Classifier",
        "F1-spam (mean)", "F1-spam (std)",
        "Recall-spam", "Precision-spam",
        "ROC-AUC", "Accuracy",
    ]

    for col in display.columns[2:]:
        display[col] = display[col].map("{:.4f}".format)

    # Markdown table
    lines = ["| " + " | ".join(display.columns) + " |"]
    lines.append("| " + " | ".join(["---"] * len(display.columns)) + " |")
    for _, row in display.iterrows():
        lines.append("| " + " | ".join(str(v) for v in row) + " |")

    return "\n".join(lines)


def write_report(df: pd.DataFrame) -> Path:
    """Write a Markdown model comparison report to reports/."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    report_path = REPORTS_DIR / "model_comparison.md"

    best = df.iloc[0]
    table = format_results_table(df)

    content = f"""# Model Comparison Report

Generated by `src/spam_detector/evaluate.py`.

## Selection Criterion

Models are ranked by **CV F1-spam** (5-fold StratifiedKFold), which balances
precision and recall for the minority (spam) class.
Accuracy alone is a poor metric here because a classifier that always predicts
"ham" would achieve ~71% accuracy on this dataset.

## Results

{table}

## Winner

**Normalisation:** `{best['normalisation']}`  
**Classifier:** `{best['classifier']}`  
**CV F1-spam:** {best['cv_f1_spam_mean']:.4f} ± {best['cv_f1_spam_std']:.4f}  
**CV Recall-spam:** {best['cv_recall_spam_mean']:.4f}  
**CV ROC-AUC:** {best['cv_roc_auc_mean']:.4f}  

## Notes

- All experiments use the same TF-IDF configuration (ngram_range=(1,2), min_df=2,
  max_df=0.95, sublinear_tf=True, max_features=50000).
- The TF-IDF vectorizer is fit inside each CV fold via sklearn.Pipeline,
  so there is no data leakage between folds.
- LinearSVC does not natively support predict_proba; it is wrapped in
  CalibratedClassifierCV when selected as the final model.
- The test set was held out entirely and used only for the final evaluation.
"""

    report_path.write_text(content, encoding="utf-8")
    logger.info("Report written → %s", report_path)
    return report_path


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s  %(message)s")
    df = load_cv_results()
    path = write_report(df)
    print(f"Report saved to: {path}")
    print("\nTop 5 combinations:")
    print(df.head(5).to_string(index=False))


if __name__ == "__main__":
    main()
